# Generated by scripts/cli-release.mjs — do not edit by hand.
class M8t < Formula
  desc "CLI for managing m8t-stack deployments on Azure / Microsoft Agent Foundry"
  homepage "https://github.com/m8t-run/m8t"
  url "https://registry.npmjs.org/@m8t-stack/cli/-/cli-0.2.14.tgz"
  sha256 "252d02507fbacd1b9a3c0feb843f9dd3e047a74559a79a37f53b920f6e54a3b9"
  license "MIT"
  version "0.2.14"

  depends_on "node"

  def install
    system "npm", "install", *std_npm_args
    bin.install_symlink Dir["#{libexec}/bin/*"]
  end

  test do
    assert_match version.to_s, shell_output("#{bin}/m8t version")
  end
end
