# Generated by scripts/cli-release.mjs — do not edit by hand.
class M8t < Formula
  desc "CLI for managing m8t-stack deployments on Azure / Microsoft Agent Foundry"
  homepage "https://github.com/m8t-run/m8t"
  url "https://registry.npmjs.org/@m8t-stack/cli/-/cli-0.2.1.tgz"
  sha256 "98691cbfa6d79a5543f78e62603d19253e1ee3327f09b6f196f7e3499cf607a9"
  license "MIT"
  version "0.2.1"

  depends_on "node"

  def install
    system "npm", "install", *std_npm_args
    bin.install_symlink Dir["#{libexec}/bin/*"]
  end

  test do
    assert_match version.to_s, shell_output("#{bin}/m8t version")
  end
end
