# Generated by scripts/cli-release.mjs — do not edit by hand.
class M8t < Formula
  desc "CLI for managing m8t-stack deployments on Azure / Microsoft Agent Foundry"
  homepage "https://github.com/m8t-run/m8t"
  url "https://registry.npmjs.org/@m8t-stack/cli/-/cli-0.2.8.tgz"
  sha256 "f4bf3f22178f86044ad58b087e1b6257e163fa141baa4005d30b68e432af0f5e"
  license "MIT"
  version "0.2.8"

  depends_on "node"

  def install
    system "npm", "install", *std_npm_args
    bin.install_symlink Dir["#{libexec}/bin/*"]
  end

  test do
    assert_match version.to_s, shell_output("#{bin}/m8t version")
  end
end
